ARK - 9 Oauth 2 로그인 연동 기능
Ark-inflearn/inflearn-clone-back pull request #119
Opened 2021-09-06 13:27 UTC by lsj8367

조금 바빴던 탓에 늦게 Oauth2를 연동하게 되었습니다.

일단 dev, prod yaml에서 깃허브는 oauth 연동을 다르게 설정해주었습니다.

페이스북 연동 같은 경우에는 같기 때문에 `application.yaml`에서 설정을 해주었습니다.

2021-09-06 13:28 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +                                .failureUrl("/loginFailure")
현재 이부분을 어떻게 진행해야하는지 조금 더 고민해봐야할 사항입니다.

2021-09-07 00:26 UTC, shirohoo commented on src/main/resources/application.yml
> +            client-secret: 8e6b34d5dbad3f03c4c70ecd95661530
요기는 ENC(가 없어도 되나요?

2021-09-07 00:26 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +                                .failureUrl("/loginFailure")
`CustomOauth2UserService`에서 예외를 던져주고, `FailureHandler`에서 예외체크하여 분기한담에 `302`와 모종의 헤더를 심어 응답하면 됩니다.

이후 프론트단에서 그 정보를 토대로 페이스북 이슈로 인한 가입인지를 판별해서 데이터를 보내줄 수 있고요.

HTTP의 `무상태성`, `비연결성`은 이렇게처리해야 됩니다.

2021-09-07 00:26 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
> +        String registrationId = userRequest.getClientRegistration().getRegistrationId();
`디미터 법칙` 위반이네요.

2021-09-07 14:20 UTC, lsj8367 commented on src/main/resources/application.yml
> +            client-secret: 8e6b34d5dbad3f03c4c70ecd95661530
요거는 예전거라서 반영이 안된걸로 보이네요 이후 파일에서는 다 암호화 처리 진행했습니다

2021-09-13 00:30 UTC, shirohoo requested changes

2021-09-13 00:30 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/config/model/HttpResponse.java
> +
생성자 오버로딩 👍

2021-09-13 00:30 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/repository/MemberRepository.java
> +    Optional<Member> findBySocialId(String socialId);
사소하지만.. `final`이 없습니다 ㅋ.ㅋ

2021-09-13 00:30 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/handler/Oauth2AuthenticationSuccessHandler.java
>              response.setStatus(HttpStatus.FOUND.value());
이부분은  `response.setStatus`가 인수로 HttpStatus 타입이 아닌 int 타입만 받을 수 있다고 한다면 그냥  `302`로 하드코딩해도 무방할 것 같아요.

`response.setStatus(302);`

그냥 읽어봤을때 매직넘버라는 느낌은 안드네요. 오히려 이편이 더 가독성이 좋은 것 같습니다.

2021-09-13 06:22 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/repository/MemberRepository.java
> +    Optional<Member> findBySocialId(String socialId);
반영하도록 하겠습니다 😂

2021-09-13 06:23 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/handler/Oauth2AuthenticationSuccessHandler.java
>              response.setStatus(HttpStatus.FOUND.value());
사실 이부분도 Enum으로 명시되어있었다면 그대로 쓰는것이 나았겠지만 `value()`가 있어서 상당히 거슬렸던 부분입니다.
고려해서 적절한 방법으로 고쳐볼게요 👍

2021-09-15 04:46 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/config/model/HttpResponse.java
> +
👍

2021-09-15 12:47 UTC, shirohoo approved these changes

2021-09-15 12:50 UTC, merged