ARK-16 비밀번호 변경 기능
Ark-inflearn/inflearn-clone-back pull request #152
Opened 2021-10-02 08:56 UTC by lsj8367

[![ARK-16](https://badgen.net/badge/JIRA/ARK-16/0052CC)](https://jira.company.com/browse/ARK-16) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Ark-inflearn&utm_campaign=badge_info)

### SMTP를 이용하여 메일 보내기

SMTP를 이용하여 메일 보내기를 구현하였습니다. 구현한 API목록은 아래와 같습니다.

- `/api/v1/member/informationMail`
  - 인증키가 들어있는 메일을 **비밀번호를 찾고자하는 이메일에 전송** 해줍니다.
- `/api/v1/member/check`
  - 발송된 메일에 들어있는 인증번호와 서버가 갖고있는 인증번호를 비교합니다.
- `/api/v1/member/changePassword`
  - 비밀번호를 변경하는 api입니다.

---

구글은 ssl 인증서 문제가 있어서 네이버 메일 `smtp.naver.com`로 구축한 상태입니다.
이슈에 올려져있는 플로우대로 구현을 진행하였습니다.

2021-10-02 10:18 UTC, MinChul-Son reviewed
고생하셨습니다. 승재님!! 구글 덕분에 고생을...

제 코맨트에 대한 답변 부탁드려요.

2021-10-02 10:18 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/domain/member/controller/MemberApiController.java
> +        javaMailSender.send(memberService.informationEmail(requestMap.get("email")));
이 부분은 서비스 로직에서 처리하는게 좋지 않을까요?

컨트롤러에서는 `memberService.informationEmail`만을 호출하여 이메일을 넘겨주는 역할만 하도록요

2021-10-02 10:18 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/domain/member/service/MemberService.java
> +    }
`javaMailSender.send()`을 하는 `private` 메소드를 만들고 여기서 한번에 처리하게 하는게 어떨까하는게 저의 생각입니다.

2021-10-02 10:22 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/domain/member/utils/MailEnum.java
> +    FROM_ADDRESS("lsj8367@naver.com"),
이렇게되면 메일을 보내는 발송자는 승재님이 되시는건가요??

2021-10-02 11:57 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/member/utils/MailEnum.java
> +    FROM_ADDRESS("lsj8367@naver.com"),
이거는 `application.yaml`에 설정된 값하고 매칭을 시켰는데 default가 되는지 확인해봐야 될것 같아요

2021-10-02 11:57 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/member/controller/MemberApiController.java
> +        javaMailSender.send(memberService.informationEmail(requestMap.get("email")));
네 저도 이부분에서 조금 고민을 했었는데 아무래도 그게 나은방향인것 같아요 🤔

2021-10-02 11:58 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/member/service/MemberService.java
> +    }
윗부분과 같은 내용의 조언이시네요 한번 수정해보도록 하겠습니다 😄

2021-10-02 13:40 UTC, shirohoo reviewed
코드 잘봤습니다.
고생하셨습니다 !

2021-10-02 13:40 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/member/controller/MemberApiController.java
> +
member 컨트롤러에 두기보단 mail 관련 컨트롤러를 따로 두는게 더 낫지않을까요?

2021-10-02 13:40 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/configuration/security/model/entity/Member.java
> +    @Setter
`setPassword` 보단 `changePassword`나 `updatePassword` 같은이름으로 메서드를 만드는게 더 직관적일 것 같습니다.

2021-10-04 09:29 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/member/controller/MemberApiController.java
> +
반영하겠습니다 😄

2021-10-04 11:01 UTC, MinChul-Son approved these changes
코드 잘봤습니다!! 고생하셨어요 승재님!

2021-10-04 14:00 UTC, shirohoo requested changes
코드 잘봤습니다 👍

코멘트 몇개 남겼으니 확인 부탁드립니다 !

전체적으로 `final` 이 많이 누락된 것 같습니다.

고생하셨습니다 !

2021-10-04 14:00 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/mail/controller/MailApiController.java
> +    @PostMapping("/informationMail")
- /information-mail
- /information_mail
- /informationMail

🤔

2021-10-04 14:00 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/mail/service/MailService.java
> +    public void informationEmail(String email) {
인증메일인거죠?

이름이 `verificationMail` 은 어떨까요?

2021-10-04 14:00 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/mail/service/MailService.java
> +        log.info("email sending completed.");
`javaMailSender.send(mimeMessage)` 요녀석때문에 추상화레벨이 깨지는느낌이 나네요

2021-10-04 14:00 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/mail/service/MailService.java
> +        return stringBuilder.toString();
`StringBuilder` 사용 👍

이름을 `mailBuilder` 같은것으로 선언하는게 좀 더 직관적일 것 같습니다.

그리고 끝라인에 세미콜론(;)을 붙여서 끝내지말고 `append`를 계속 체이닝하는게 더 깔끔할 것 같아요.

2021-10-04 14:02 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/mail/service/MailService.java
> +        return stringBuilder.toString();
체이닝 참고하겠습니다.
그리고 아직 이 부분에 노아님과 합의되지 않은 곳이 `TODO` 주석으로 묶여있어요
저 부분이 타협되면 이 기능을 마무리 짓도록 하겠습니다. 😀

2021-10-04 14:04 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/mail/service/MailService.java
> +    public void informationEmail(String email) {
변경하기 링크를 내려주는 이메일 입니다. 메서드 네이밍에 대해서 조금 더 생각해볼게요

2021-11-08 01:54 UTC, shirohoo approved these changes

2021-11-08 01:56 UTC, merged