ARK-3 스프링 시큐리티 Oauth2 구축
Ark-inflearn/inflearn-clone-back pull request #76
Opened 2021-08-27 15:03 UTC by lsj8367

[![ARK-3](https://badgen.net/badge/JIRA/ARK-3/0052CC)](https://jira.company.com/browse/ARK-3) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Ark-inflearn&utm_campaign=badge_info)

여러모로 부족했던 구현이었던것 같습니다.
구글 로그인 연동은 완료 되었으니 점차 네이버, 깃허브, 카카오 연동까지 생각중인데
의견 주시면 감사할것 같습니다.

![스크린샷 2021-08-27 오후 11 21 16](https://user-images.githubusercontent.com/74235102/131142256-7b318c75-9d47-426d-8014-fb97cd698991.png)

그림과 같이 나오는것 잘 확인하였습니다.
리뷰 부탁드립니다. 😱

실행링크는 localhost:8080/oauth2/authorization/google

2021-08-28 00:12 UTC, MinChul-Son requested changes

2021-08-28 00:12 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/domain/security/model/Member.java
> +    }
창훈님의 의견에 동의합니다!

2021-08-28 02:19 UTC, lsj8367 commented on src/test/java/com/ark/inflearnback/domain/security/repository/MemberRepositoryTest.java
> +        assertThat(result.getEmail()).isEqualTo("lsj@gmail.com");
네 수정하겠습니다

2021-08-28 02:19 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/model/OAuthAttributes.java
> +    }
변경되면 반영하도록 하겠습니다🤩

2021-08-28 02:26 UTC, lsj8367 commented on src/main/resources/application.yml
active 설정 따라서 oauth가 그부분만 먹을것 같아요 아래로 수정할게요

2021-08-28 02:27 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/model/OAuthAttributes.java
> +    }
오타 맞습니다. 수정할게요 😭

2021-08-28 07:53 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
>          Role role = Role.of("ROLE_USER", "사용자", false);
여기 `"ROLE_USER"` 에러나지 않아요?

RoleType이 들어가야 할 것 같은데 🤔

2021-08-28 07:54 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
> +        Role role = Role.of(RoleType.ROLE_MEMBER, "사용자", false);
https://github.com/Ark-inflearn/inflearn-clone-back/pull/76#discussion_r697831992

반영되기 전 코드였군여 😅

2021-08-28 08:03 UTC, shirohoo requested changes
QClass가 VCS에 포함된 것 같네요. .gitignore에 추가하신 만큼 기존에 포함 된 QClass는 삭제해주시는 게 좋을 것 같아요.

잘 봤습니다 !

2021-08-28 08:03 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/config/jasypt/JasyptConfig.java
> +    @Bean("jasyptStringEncryptor")
`@Autowired`는 타입기반으로 주입해주기 때문에 빈 이름을 줄 필요가 없을 것 같아요.

그리고 `@Profile`로 운영, 개발용 빈을 구분해놓기도 했구요.

2021-08-28 08:03 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/config/jasypt/JasyptConfig.java
> +        config.setStringOutputType("base64");
코드가 너무 길고 devEncryptor() 와 중복되는 내용이 많은 것 같아서 메서드 추출 리팩토링을 하는게 좋을 것 같다는 생각이 들어요.

2021-08-28 13:50 UTC, MinChul-Son requested changes
`QType` 클래스 삭제하고, `formLogin`부분에 대해서는 이야기가 조금 필요하겠네요!
고생하셨습니다 승재님!

2021-08-28 13:50 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +                .formLogin(login ->
이 부분은 제가 작성한 코드에서 `disabled` 처리하였는데 코드가 합쳐지면 어떻게 되려나요?..
한번 논의를 해야겠네요.

2021-08-29 03:45 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
> +        return new DefaultOAuth2User(Collections.singleton(new SimpleGrantedAuthority(role.getRoleType().get())),
네 수정해보도록 할게요 😄

2021-08-29 03:45 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/model/OAuthAttributes.java
> +        return ofGoogle(nameAttributeKey, attributes);
네이버 인증을 위해서 놔뒀었는데 확인해보고 수정할게요

2021-08-29 03:59 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/config/jasypt/JasyptConfig.java
> +    @Bean("jasyptStringEncryptor")
```yml
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
```
application.yml설정에서 이렇게 설정해줘서 bean 이름을 명시했어요. 빼면 문제가 생길것 같아서 그랬습니다.

2021-08-29 05:10 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/model/OAuthAttributes.java
> +                .email((String) attributes.get("email"))
네 어제 고민한 결과 `sub`, `email`, `email_verified` 외에 필요한 필드로 구성해봤습니다.

2021-08-29 05:10 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/config/jasypt/JasyptConfig.java
> +        config.setStringOutputType("base64");
바로 확인하고 수정했습니다👍

2021-08-29 05:13 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +                .formLogin(login ->
네 맞습니다. `formLogin`은 그냥 임의의 기본값으로 설정되어있어서 확인이 필요한 문제같습니다. 🤔

2021-08-29 05:52 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +                .formLogin(login ->
어차피 처리주체가 독립돼있어서 아예 사용하지 않는것도 좋을 것 같고, 내비둬도 상관없을 것 같아요.

2021-08-29 06:03 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
> +        return oAuthAttributes.customDefaultOauth2User();
로그인은 일반적으로 수많은 사용자가 정말 수시로 하는 작업이고 이미 `HttpLog`에서 기본적인 모든 로그를 DB에 남기기 때문에 굳이 파일에 이렇게 많이 로깅할 내용은 아닌 것 같다는 생각이 듭니다 !

파일에 로깅할 내용은 정말 중요한 것들, 예를들면 회원가입, 결제정보 같은 것들만 있어야 할 것 같아요.

큰 회사에서는 하루에 텍스트 로깅파일만 기가단위로 나오는 곳들도 있으니 한번 고민해 볼 문제인 것 같아요.

2021-08-29 06:25 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
> +    }
빌더 패턴 생각해보시면 `Builder` 라는 내부 정적 클래스를 만들고 그안에 메서드로 변수를 할당해줘서 OAuthAttributes.Builder().name()... 으로 되니까 그거 생각하면 private으로 둬도 builder가 동작 하는것 같습니다 :)

2021-08-29 06:33 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
> +    }
> 오 이거 private 생성자에 빌더만 선언해도 `public`으로 열리나요?

빌더 패턴 생각해보시면 Builder 라는 내부 정적 클래스를 만들고 그안에 메서드로 변수를 할당해줘서 OAuthAttributes.Builder().name()... 으로 되니까 그거 생각하면 private으로 둬도 builder가 동작 하는것 같습니다 :)

2021-08-29 10:34 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
> +        return oAuthAttributes.customDefaultOauth2User();
저것만 로그인한다고 생각하고 구현했던것 같네요 큰 레이어를 못보고 지나쳤었네요.
수정하겠습니다.

2021-08-29 11:16 UTC, MinChul-Son approved these changes
잘봤습니다. 승재님 고생하셨어요😀

2021-08-29 11:16 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/config/jasypt/JasyptConfig.java
> +    public PooledPBEStringEncryptor encryptorSetting(final String password) {
👍👍👍

2021-08-29 11:16 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
> -        log.info("Oauth2 User Login Service....");
로그 삭제 확인했습니다.👍👍

2021-08-29 11:52 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
> +        boolean isEmailVerified = oAuth2User.getAttribute("email_verified");
이거 세개는 굳이 클래스변수로 사용하지 않아도 될 것 같아요.
이미 클래스변수에 `oAuth2User`가 있으니까 저 세개를 반환해주는 메서드를 열어주는게 더 좋을 것 같다고 생각합니다.

```java
public class OAuthAttributes {
    private final OAuth2User oAuth2User;
    private final String registrationId;
    private final String userNameAttributeName;

    @Builder
    private OAuthAttributes(final OAuth2User oAuth2User, final String registrationId, final String userNameAttributeName, final String sub, final String email, final boolean isEmailVerified) {
        if (!this.isEmailVerified()) {
            throw new Oauth2UserNotVerifiedException("인증되지 않은 사용자입니다.");
        }

        this.oAuth2User = oAuth2User;
        this.registrationId = registrationId;
        this.userNameAttributeName = userNameAttributeName;
    }

    public static OAuthAttributes of(final OAuth2User oAuth2User, OAuth2UserRequest userRequest) {
        return OAuthAttributes.builder()
                .oAuth2User(oAuth2User)
                .registrationId(userRequest.getClientRegistration().getRegistrationId())
                .userNameAttributeName(userRequest.getClientRegistration()
                        .getProviderDetails()
                        .getUserInfoEndpoint()
                        .getUserNameAttributeName())
                .build();
    }

    public DefaultOAuth2User customDefaultOauth2User() {
        return new DefaultOAuth2User(Collections.singleton(new SimpleGrantedAuthority(RoleType.MEMBER.get())),
                oAuth2User.getAttributes(), this.userNameAttributeName);
    }

    public String getSub() {
        return oAuth2User.getAttribute("sub");
    }

    public String getEmail() {
        return oAuth2User.getAttribute("email");
    }

    public boolean isEmailVerified() {
        return oAuth2User.getAttribute("email_verified");
    }
}
```

2021-08-30 02:00 UTC, shirohoo requested changes

2021-08-30 02:00 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
>          this.userNameAttributeName = userNameAttributeName;
여기 포매팅이 약간 이상하네여 😯

2021-08-30 02:09 UTC, shirohoo requested changes

2021-08-30 02:09 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
> +    public static OAuthAttributes of(final OAuth2User oAuth2User, OAuth2UserRequest userRequest, boolean isEmailVerified) {
서비스 클래스에서 `oAuth2User.getAttribute("email_verified")`를 호출해서 `boolean` 파라미터로 넣으신 이유가 있나요?

검증 코드를 팩토리에 넣자니 `isVerified()`가 정적 메서드가 되어야 하고, 생성자에 넣자니 좀 별로인 것 같아서라면 생성자에 넣는걸 추천드립니다.

실제로 JDK의 많은 공식 라이브러리들도 보면 생성자에서 많은 일을 하고 있어요.

초기 객체의 초기화를 책임지는 부분이니, 안전한 객체의 생성을 위해서 하는 일이라면 생성자에 다 몰아넣어도 무방할 것 같아요.

2021-08-30 02:09 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
> +        return oAuth2User.getAttribute("email_verified");
이름이 불분명한 것 같습니다.

구현부 코드를 보면 `email`이 검증됐는지 여부를 반환하는 메서드인데, 실제 이 코드를 사용하는 클라이언트 입장에서는 `OAuthAttributes`가 검증됐는지를 반환하는 걸로 착각할 수 있을 것 같아요.

2021-08-30 02:09 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
> +        httpSession.setAttribute("Oauth20Authentication", new SessionMember(oAuthAttributes.getEmail()));
가즈아 ~~ 🤪

2021-08-30 03:08 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
> +    public static OAuthAttributes of(final OAuth2User oAuth2User, OAuth2UserRequest userRequest, boolean isEmailVerified) {
정확히 고민한 부분을 짚어주셨네요 생성자에 넣어서 반영하도록 할게요

2021-08-30 03:13 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
>          this.userNameAttributeName = userNameAttributeName;
책에서 읽은걸 반영해봤는데 컨벤션이 더 중요했습니다. 수정할게요 😭

2021-08-31 06:39 UTC, shirohoo approved these changes

2021-08-31 06:43 UTC, merged