ARK-7 이메일 & 비밀번호 방식의 로그인 기능
Ark-inflearn/inflearn-clone-back pull request #86
Opened 2021-08-28 13:32 UTC by MinChul-Son

방향을 못잡고 있었는데 창훈님 덕에 어느정도 전체적인 동작 과정을 파악했습니다.
1. `JsonLoginFilter`
2. `CustomAuthenticationProvider`
3. `CustomUserDetailsService`

이 순서로 동작합니다.
`JSON` 방식의 로그인 구현은 처음이라 피드백 부탁드립니다.🙏

`AuthenticationHandler`는 현재는 `SuccessHandler`만 구현되어 있습니다. 
로그인에 성공했다면 `HTTP 상태코드 200`을 반환합니다.

현재는 필터를 추가하는 방식인데 이걸 별도의 `Configurer`로 분리하여 아예 갈아끼우는 방식도 있다고 합니다.

### 로그인 실패
![image](https://user-images.githubusercontent.com/60773356/131219631-29bb07f0-ed6b-4569-a094-a11702757cf3.png)

### 로그인 성공
![image](https://user-images.githubusercontent.com/60773356/131219647-eb52309a-0415-42ae-9899-caea6f903716.png)

2021-08-28 17:50 UTC, shirohoo requested changes

2021-08-28 17:51 UTC, shirohoo commented
전체적으로 스프링 시큐리티의 아키텍처를 제대로 활용하고 있지 못하다는 생각이 들었어요 😭

제가 한번 간단하게 작성해서 커밋해두었으니 한번 살펴보시면 좋을 것 같습니다 ! 화이팅 👏👏👏

2021-08-29 03:44 UTC, lsj8367 requested changes

2021-08-29 03:44 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +@Order(1)
Order 가 없다면 빈 주입 우선순위가 꼬여서 에러를 발생시키나요? 궁금합니다.

2021-08-29 03:44 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/filter/RestLoginProcessingFilter.java
> +        return "application/json".equals(request.getHeader("Content-Type"));
비교하는 문자열이 `request.getHeader` 의 content-type을 json인지 확인하는거니까
```suggestion
        return request.getHeader("Content-Type").equals("application/json"));
```
이 더 나을 것 같은데 민철님의 생각이 궁금합니다.

2021-08-29 03:44 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/token/RestAuthenticationToken.java
> +    private Object credentials;
여기도 마찬가지로 생성자에서 할당을 받고있는데요,
`final` 인자를 빼두신 이유가 있을까요? 🤔

2021-08-29 04:01 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/token/RestAuthenticationToken.java
> +    private Object credentials;
스프링 시큐리티의 `AbstractAuthenticationToken` 코드를 그대로 가져와서 확장했어요.

저도 좀 의아하긴했는데 일단 시큐리티 코드니까 믿고썼습니다.

2021-08-29 04:02 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/filter/RestLoginProcessingFilter.java
> +        return "application/json".equals(request.getHeader("Content-Type"));
`request.getHeader("application/json")` 가 `null`일 경우 `NPE`가 발생합니다.
이 방식은 보통 NPE를 회피하기 위해 `equals`를 호출하는 주체가 문자열 리터럴인, 일종의 편법이에요. 😁

2021-08-29 04:03 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +@Order(1)
제가 새벽에 정신없이 작성하다가 빼먹고 안지운 코드네요. 👍👍👍

일단 질문에 답변드리면 필터체인이 한개인 경우 `Order`가 없어도 무방합니다 ㅎ.ㅎ

2021-08-29 09:31 UTC, MinChul-Son reviewed
잘봤습니다. 창훈님 전체적인 흐름은 알겠는데 어렵네요ㅠ

2021-08-29 09:31 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +                .addFilterBefore(restLoginProcessingFilter(), UsernamePasswordAuthenticationFilter.class)
`UsernamePasswordAuthenticationFilter` 또한 `AbstractAuthenticationProcessingFilter`를 구현한 클래스이기에 이렇게가 가능한건가요?

2021-08-29 09:31 UTC, MinChul-Son commented on src/test/java/com/ark/inflearnback/annotation/EnableDockerContainers.java
> +public @interface EnableDockerContainers {
👍👍👍

2021-08-29 09:31 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +        return new CustomAuthenticationSuccessHandler(objectMapper);
👍👍👍👍

2021-08-29 09:31 UTC, MinChul-Son commented on src/main/java/com/ark/inflearnback/domain/security/filter/RestLoginProcessingFilter.java
> +public class RestLoginProcessingFilter extends AbstractAuthenticationProcessingFilter {
저희의 인증이 `email+password`로 이뤄지기 때문에 제가 구체 클래스인 `UsernamePasswordAuthenticationFilter`을 상속받아 구현했었는데, 공식 문서를 찾아보니 이는 `Form-Login` 방식을 지원하기 위해 `Spring`이 미리 만들어놓은 필터라군요. 더 확장성이 높은 상위 클래스인 `AbstractAuthenticationProcessingFilter`를 상속받아 사용하는 것이 맞겠군요..👍👍👍👍👍

2021-08-29 10:09 UTC, lsj8367 requested changes

2021-08-29 10:09 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/filter/RestLoginProcessingFilter.java
> +        }
꼼꼼한 예외처리 👍

2021-08-29 10:09 UTC, lsj8367 commented on src/main/java/com/ark/inflearnback/domain/security/filter/RestLoginProcessingFilter.java
> +        }
꼼꼼한 예외처리 👍

2021-08-29 10:17 UTC, shirohoo commented on src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
> +                .addFilterBefore(restLoginProcessingFilter(), UsernamePasswordAuthenticationFilter.class)
맞습니다 !!

2021-08-29 10:18 UTC, shirohoo approved these changes

2021-08-29 10:32 UTC, lsj8367 approved these changes

2021-08-29 10:33 UTC, merged